{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "stalwart-mail-ha.fullname" . }}
  labels:
    {{- include "stalwart-mail-ha.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "stalwart-mail-ha.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      path: {{ .Values.metrics.serviceMonitor.path }}
      scheme: {{ .Values.metrics.serviceMonitor.scheme }}
      {{- if .Values.metrics.serviceMonitor.bearerTokenSecret.name }}
      authorization:
        type: Bearer
        credentials:
          name: {{ .Values.metrics.serviceMonitor.bearerTokenSecret.name }}
          key: {{ .Values.metrics.serviceMonitor.bearerTokenSecret.key }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
