{{- if not .Values.freescout.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "freescout.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "freescout.name" . }}
    helm.sh/chart: {{ include "freescout.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  admin-email: {{ .Values.freescout.admin_email | b64enc | quote }}
  {{ if .Values.freescout.admin_pass }}
  admin-password: {{ .Values.freescout.admin_pass | b64enc | quote }}
  {{ else }}
  admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
{{- end }}
